#!/bin/bash

BASE=$(pwd)
for rc in tmux.conf gitconfig vimrc zshrc; do
  ln -sfv "$BASE/$rc" ~/."$rc"
done	

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

platform=$(uname)
if [[ $platform == 'Darwin' ]]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  brew update
  brew install \
    zsh vim neovim tmux git tectonic wget pyenv pure
else 
  rm -f ~/.tmux.conf
  grep -v reattach-to-user-namespace tmux.conf > ~/.tmux.conf
fi

if [[ ! -d ~/.fzf ]]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install --all 
fi

if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [[ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]]; then
  sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

if [[ ! -d ~/.tmux/plugins/tpm ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

git config --global user.email "oliver.xu@arup.com"
git config --global user.name "Oliver Xu"
git config --global user.signingKey C6BA47C09A13D39F
git config --global commit.gpgsign true

mkdir -p ~/.config/nvim
touch ~/.config/nvim/init.vim
ln -sf $BASE/init.vim ~/.config/nvim/init.vim
vim -es -u ~/.vimrc +PlugInstall +qa
nvim -es -u ~/.config/nvim/init.vim +PlugInstall +qa

tmux source-file ~/.tmux.conf
